### PR TITLE
Update verify version

### PR DESCRIPTION
**Pull request by aaron-collier**
Blocked by #336 

Small PR that only compares and updates the existing resource if the input version matches.

### CODE REVIEW

**Comment by jcoyne** [comment]
Why is this "Blocked"?  What is the blocker?

**Comment by aaron-collier** [comment]
Perhaps blocked is the wrong wording. I just wanted this tags to make sure that 336 went in first.

**Comment by jcoyne** [comment]
@aaron-collier do we need to reconsider the plan for this PR now that #336 is not slated for merge in the near future?

**Comment by aaron-collier** [comment]
Will rework this based on #336 work.

**Pull request closed without merging**
