### PR TITLE
Add honeybadger monitoring

### LINKED ISSUE #97: Integrate honeybadger
How do we integrate honeybadger into go stack / infra?

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #97 
Our first error: https://app.honeybadger.io/projects/54955/faults/36526098

To enable it set the environment variable:
`HONEYBADGER_API_KEY=xxxxxxxx`

### CODE REVIEW

**Comment by jcoyne** [comment]
@cmh2166 other team members removed the conditional environment stuff (e.g. `development`, `test`) I had earlier.  I'm not sure how we'd conditionally apply this without it.

**Comment by aaron-collier** [comment]
I think the question is more along the lines of could this be conditional? If `HONEYBADGER_API_KEY` is not in the environment, then not return the middleware?

**Comment by jcoyne** [comment]
@cmh2166 can you explain to me what you are seeing... as far as I can tell it just doesn't report errors to HB if you don't supply the key, but otherwise works as before.

**Comment by aaron-collier** [comment]
@jcoyne with no key:

```
DN0a233228:taco amcollie$ AWS_ACCESS_KEY_ID=999999 AWS_SECRET_KEY=1231 go run cmd/tacod/main.go 
middleware/honeybadger.go:6:2: cannot find package "github.com/honeybadger-io/honeybadger-go" in any of:
	/Users/amcollie/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/honeybadger-io/honeybadger-go (vendor tree)
	/usr/local/Cellar/go/1.9.3/libexec/src/github.com/honeybadger-io/honeybadger-go (from $GOROOT)
	/Users/amcollie/go/src/github.com/honeybadger-io/honeybadger-go (from $GOPATH)
```

**Pull request merged**
