### PR TITLE
adding sample PDF for running updated file load example in readme

### PR DESCRIPTION
**Pull request by cmh2166**
not required for merging, just adding example file for file upload

### CODE REVIEW

**Comment by jcoyne** [comment]
I'm not keen on storing binaries in this repo, especially ones we don't need (this could be any binary file). Could we add instructions on how to pull this file (using curl) from elsewhere instead?

**Comment by cmh2166** [comment]
@jcoyne just curious, why no example binaries in a repo?

**Comment by jcoyne** [comment]
@cmh2166 binaries make the git repo grow very big, it's not well suited to storing binaries as they they have to basically be stored as full files, even if we decide to remove it from HEAD, it'll have to hold that file in case you want to checkout the old version.  This is something we've run into in the hydra project https://github.com/samvera/hydra-jetty

**Comment by jcoyne** [comment]
Can we add this to the readme instead?
```
curl -L https://github.com/samvera/hyrax/raw/master/spec/fixtures/hyrax/hyrax_test4.pdf -o myfile.pdf
```

**Comment by cmh2166** [comment]
That’s fine for me

**Comment by jcoyne** [comment]
Superseded bye #431

**Pull request closed without merging**
