### PR TITLE
Update docker file to fix error when running

### LINKED ISSUE #52: Fix Docker build
With the swagger generated code we get the following error running in docker:

```
panic: Invalid schema provided to SchemaValidator: open /tmp/root404554322: no such file or directory

goroutine 1 [running]:
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/validate.NewSchemaValidator(0xc4201be000, 0x89bea0, 0xc42042f100, 0xc4204259d8, 0x4, 0xb73b00, 0xc4203c50e0, 0xc420285020)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/validate/schema.go:71 +0x106b
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.newUntypedParamBinder(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/parameter.go:46 +0x1bb
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.newUntypedRequestBinder(0xc420285020, 0xc42042f100, 0xb73b00, 0xc4203c50e0, 0xc420285230)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/request.go:39 +0x1bf
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.(*defaultRouteBuilder).AddRoute(0xc420284fc0, 0x907b83, 0x5, 0xc4203fa0c0, 0x11, 0xc4203c8380)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/router.go:290 +0x693
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.DefaultRouter(0xc420072140, 0xb73f80, 0xc42042e100, 0x898740, 0xc420473460)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/router.go:137 +0x14c
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.NewRouter(0xc420284a50, 0xb6d040, 0xc420473460, 0xc420473460, 0xc420529ca8)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/router.go:69 +0xfd
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler(0xc420284a50, 0x92b118, 0xc420513948, 0xc4203b4640)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/context.go:558 +0x7d
github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware.(*Context).APIHandler(0xc420284a50, 0x0, 0xc42047a008, 0xc4200a8048)
	/go/src/github.com/sul-dlss-labs/taco/vendor/github.com/go-openapi/runtime/middleware/context.go:549 +0xf5
github.com/sul-dlss-labs/taco/generated/restapi/operations.(*TacoAPI).Serve(0xc42042e100, 0x0, 0x0, 0x7f8f71b030a0)
	/go/src/github.com/sul-dlss-labs/taco/generated/restapi/operations/taco_api.go:286 +0x80
github.com/sul-dlss-labs/taco/generated/restapi.(*Server).Serve(0xc4200a8000, 0x92ae28, 0xc4200a8000)
	/go/src/github.com/sul-dlss-labs/taco/generated/restapi/server.go:156 +0x12f0
main.main()
	/go/src/github.com/sul-dlss-labs/taco/main.go:37 +0x196
```

### PR DESCRIPTION
**Pull request by aaron-collier**
Fixes #52

### CODE REVIEW

**Comment by cmh2166** [comment]
@aaron-collier some of the changes, docs update, on deps stuff that might help: https://github.com/sul-dlss-labs/taco/tree/fix_docker_dep_add happy to merge later if not addressed here

**Comment by aaron-collier** [comment]
Thanks @cmh2166 there are clearly more deps there than I'm grabbing here. @eefahy is working on verifying this now, so hopefully we can do a couple quick merges on this.

**Comment by jcoyne** [comment]
@aaron-collier this needs a rebase now.

**Comment by aaron-collier** [comment]
Closing this PR in order to address the docker issue separately from the circleci issue.

**Pull request closed without merging**
